// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Hds5qqnIUkG1WDs1MNntb4_60YT9bTM',
    appId: '1:481542497843:web:92aab4e6dac76fa7366546',
    messagingSenderId: '481542497843',
    projectId: 'fir-chat-98dda',
    authDomain: 'fir-chat-98dda.firebaseapp.com',
    storageBucket: 'fir-chat-98dda.appspot.com',
    measurementId: 'G-WNL91DKJB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEj6j8gK4Q-JvdARZnhD2d8k0OaorbKmc',
    appId: '1:481542497843:android:a043d6bc5853bee8366546',
    messagingSenderId: '481542497843',
    projectId: 'fir-chat-98dda',
    storageBucket: 'fir-chat-98dda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqpATfOQJgKPFFF5t_oYHqoZcM-aZepcY',
    appId: '1:481542497843:ios:fd51e60570b7ae30366546',
    messagingSenderId: '481542497843',
    projectId: 'fir-chat-98dda',
    storageBucket: 'fir-chat-98dda.appspot.com',
    iosBundleId: 'com.novahumail.firebasechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqpATfOQJgKPFFF5t_oYHqoZcM-aZepcY',
    appId: '1:481542497843:ios:fd51e60570b7ae30366546',
    messagingSenderId: '481542497843',
    projectId: 'fir-chat-98dda',
    storageBucket: 'fir-chat-98dda.appspot.com',
    iosBundleId: 'com.novahumail.firebasechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Hds5qqnIUkG1WDs1MNntb4_60YT9bTM',
    appId: '1:481542497843:web:300df6ddd4364ef6366546',
    messagingSenderId: '481542497843',
    projectId: 'fir-chat-98dda',
    authDomain: 'fir-chat-98dda.firebaseapp.com',
    storageBucket: 'fir-chat-98dda.appspot.com',
    measurementId: 'G-HS5DLNTWRX',
  );
}
